# Generated by Django 3.1.1 on 2020-09-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='img',
        ),
    ]
