# Generated by Django 3.1.1 on 2020-09-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0002_remove_face_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='emp_id',
        ),
    ]
