# Generated by Django 3.1.1 on 2020-09-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0003_remove_face_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='face',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
