# Generated by Django 3.1.1 on 2020-09-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0004_auto_20200914_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='emp_id',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
