# Generated by Django 3.1.1 on 2020-09-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0005_face_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='face',
            name='emp_id',
            field=models.TextField(),
        ),
    ]
