# Generated by Django 3.1.1 on 2020-09-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0009_auto_20200915_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=12),
            preserve_default=False,
        ),
    ]
