# Generated by Django 3.1.1 on 2020-09-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0010_face_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='face',
            name='emp_id',
            field=models.TextField(auto_created=True),
        ),
    ]
