# Generated by Django 3.1.1 on 2020-09-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0011_auto_20200917_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='created',
        ),
    ]
